#pragma once

/* 클라이언트에 존재하는 모든 클래스가 인클루드해야할 내용을 담는다. */
#include <process.h>
#include "Engine_Defines.h"
namespace Client
{
	enum CHARACTER_TYPE { SWORD_MAN, DESTROYER, ENGINEER, CHARACTER_END };
	static const wstring wstrCharacterTypeNames[CHARACTER_TYPE::CHARACTER_END]{ L"SWORDMAN", L"DESTROYER", L"ENGINEER" };
	
	enum PART_TYPE { HEAD, HAIR, FACE, BODY, PART_END };
	static const wstring wstrPartTypeNames[PART_TYPE::PART_END]{ L"HEAD", L"HAIR", L"FACE", L"BODY" };

	enum SWORDMAN_HEAD_MODEL_TYPE { };
	enum SWORDMAN_HAIR_MODEL_TYPE { };
	enum SWORDMAN_FACE_MODEL_TYPE { };
	enum SWORDMAN_BODY_MODEL_TYPE { };

	enum DESTROYER_HEAD_MODEL_TYPE { };
	enum DESTROYER_HAIR_MODEL_TYPE { };
	enum DESTROYER_FACE_MODEL_TYPE { };
	enum DESTROYER_BODY_MODEL_TYPE { };

	enum ENGINEER_HEAD_MODEL_TYPE { };
	enum ENGINEER_HAIR_MODEL_TYPE { };
	enum ENGINEER_FACE_MODEL_TYPE { };
	enum ENGINEER_BODY_MODEL_TYPE { };

	enum WITCH_HEAD_MODEL_TYPE { };
	enum WITCH_HAIR_MODEL_TYPE { };
	enum WITCH_FACE_MODEL_TYPE { };
	enum WITCH_BODY_MODEL_TYPE { };
	
	enum ELEMENTAL_TYPE { FIRE, WATER, WOOD, LIGHT, DARK, ELEMENTAL_END};

	enum LAYER_TYPE
	{
		LAYER_TERRAIN,
		LAYER_SKYBOX,
		LAYER_CAMERA,
		LAYER_BACKGROUND,
		LAYER_TREEROCK,
		LAYER_PROP,
		LAYER_GRASS,
		LAYER_ROAD,
		LAYER_BUILDING,
		LAYER_MOUNTAIN,
		LAYER_PLAYER,
		LAYER_CHARACTER,
		LAYER_MONSTER,
		LAYER_NPC,
		LAYER_PROJECTILE,
		LAYER_EFFECT,
		LAYER_GROUND,
		LAYER_TRAIL,
		LAYER_UI,
		LAYER_ETC,
		LAYER_WEAPON,
		LAYER_DYNAMIC,
		LAYER_END
	};


	enum OBJ_TYPE
	{
		OBJ_BACKGROUND,
		OBJ_BUILDING,
		OBJ_CAMERA,
		OBJ_CHARACTER,
		OBJ_WEAPON,
		OBJ_PLAYER,
		OBJ_MONSTER,
		OBJ_PROP,
		OBJ_EFFECT,
		OBJ_PARTICLE,
		OBJ_TERRAIN,
		OBJ_UI,
		OBJ_DUMMY,
		OBJ_GROUND,
		OBJ_TRAIL,
		OBJ_TREEROCK,
		OBJ_GRASS,
		OBJ_NPC,
		OBJ_DYNAMIC,
		OBJ_END
	};

	
	enum LEVELID { LEVEL_STATIC, LEVEL_LOGO, LEVEL_TEST, LEVEL_LOADING,
		LEVEL_LOBBY, LEVEL_EVERMORE, LEVEL_KINGDOMHALL, LEVEL_ICELAND, LEVEL_WITCHFOREST,
		LEVEL_DUMMY, LEVEL_TOOL = 99, LEVEL_END };

	const unsigned int		g_iWinSizeX = 1600;
	const unsigned int		g_iWinSizeY = 900;

}

extern HWND g_hWnd;
extern HINSTANCE g_hInstance;

#define SERVER_IP		L"192.168.1.33"
#define SERVER_PORT		7777
#define IMGUI_NEW_LINE ImGui::NewLine()
#define IMGUI_SAME_LINE ImGui::SameLine()


using namespace Client;
